name: rain_wise
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^6.0.0
  collection: ^1.19.1
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dotted_border: ^3.1.0
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  dropdown_button2: ^2.3.9
  file_picker: ^10.2.0
  firebase_analytics: ^12.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^3.1.0
  from_css_color: ^2.0.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^7.1.1
  hooks_riverpod: ^2.6.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_path: ^0.8.0
  json_serializable: ^6.9.5
  mime_type: ^1.0.1
  page_transition: ^2.2.1
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.2
  sign_in_with_apple: ^7.0.1
  sqlite3: ^2.9.0
  sqlite3_flutter_libs: ^0.5.39
  stream_transform: ^2.1.1
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_player: ^2.9.3

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  drift_dev: ^2.28.0
  flutter_lints: ^6.0.0

  flutter_test:
    sdk: flutter

  freezed: ^3.1.0
  freezed_lint: ^0.0.10
  go_router_builder: ^3.0.0
  lints: ^6.0.0
  riverpod_generator: ^2.6.5

flutter:
  generate: true
  uses-material-design: true
