name: rain_wise
description: A comprehensive Flutter mobile app for farmers, gardeners, and weather enthusiasts to meticulously log rainfall from multiple custom gauges and transform that data into actionable insights through powerful charting and historical analysis.

publish_to: 'none'

version: 1.0.0+1
repository: https://github.com/the-user-created/RainWise

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  dotted_border: ^3.1.0
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  file_picker: ^10.2.0
  firebase_analytics: ^12.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  freezed_annotation: ^3.1.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  hooks_riverpod: ^3.0.0
  in_app_review: ^2.0.11
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_path: ^0.8.0
  json_serializable: ^6.9.5
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.0
  share_plus: ^12.0.0
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  sqlite3: ^2.9.2
  sqlite3_flutter_libs: ^0.5.40
  stream_transform: ^2.1.1
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.8.0
  dart_pubspec_licenses: ^3.0.10
  drift_dev: ^2.28.0
  flutter_lints: ^6.0.0

  flutter_test:
    sdk: flutter

  freezed: ^3.1.0
  freezed_lint: ^0.0.10
  go_router_builder: ^4.0.1
  lints: ^6.0.0
  riverpod_generator: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - CHANGELOG.md
    - assets/
    - assets/icon/

flutter_launcher_icons:
  # === Android settings ===
  android: true
  min_sdk_android: 21
  # The adaptive icon settings below will override this for Android 8.0+.
  image_path_android: "assets/icon/icon-foreground.png"
  # The background color for the adaptive icon. Using the app's secondary color.
  adaptive_icon_background: "#6995A7"
  # The foreground layer of the adaptive icon (logo with transparency).
  adaptive_icon_foreground: "assets/icon/icon-foreground.png"
  # A monochrome version of the foreground for Android 13+ themed icons.
  adaptive_icon_monochrome: "assets/icon/icon-monochrome.png"
  # Adds a 16% padding around the foreground image. This is the default but is
  # included here for clarity and to prevent the logo from touching the edges.
  adaptive_icon_foreground_inset: 16

  # === iOS settings ===
  ios: true
  # Explicit path for the standard iOS icon (1024x1024, no transparency).
  image_path_ios: "assets/icon/icon-ios.png"
  # Required by Apple. Removes the alpha channel from the final standard icon.
  remove_alpha_ios: true
  # Defines the background color to use when remove_alpha_ios is true.
  # This acts as a safeguard if the source image has stray transparent pixels.
  background_color_ios: "#ffffff"
  # Path to the transparent icon for iOS 18+ Dark Mode.
  image_path_ios_dark_transparent: "assets/icon/icon-ios-dark.png"
  # Path to the grayscale, transparent icon for iOS 18+ Tinted Mode.
  image_path_ios_tinted_grayscale: "assets/icon/icon-ios-tinted.png"
  desaturate_tinted_to_grayscale_ios: true
